# Generated by Django 3.0.7 on 2020-07-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
