# Generated by Django 3.0.7 on 2020-07-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200708_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
