# Generated by Django 3.0.7 on 2020-07-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200708_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='contact_number',
            field=models.CharField(max_length=12),
        ),
    ]
