# Generated by Django 3.0.7 on 2020-07-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200708_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='school',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
