# Generated by Django 3.0.7 on 2020-07-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200709_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='school',
            new_name='school_id',
        ),
    ]
