# Generated by Django 3.0.7 on 2020-07-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200709_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.School'),
        ),
    ]
